.TH XDSC 1 "9 December 2013"
.SH NAME
\fIxdsc\fR \- X interface to the discuss system
.SH SYNOPSIS
.B xdsc [OPTIONS]
.SH DESCRIPTION
The
.I xdsc
program provides a window-oriented user interface to the discuss system.
It uses the python-discuss libraries.  Entering replies or new
transactions is performed in an external editor, which defaults
to 'gedit' by default, but may be overridden by the DISCUSS_EDITOR
environment variables.

.SH OPTIONS
.I --debug [ui|discuss]
.RS
Print debugging messages to stderr concerning the user interface (ui) or
discuss subsystem (discuss), as specified.  This option may be specified
more than once.
.RE

.I --timeout n
.RS
Specify the timeout for connections to discuss servers, in
seconds. (defaults to 3)
.RE

.I --ui ui_file
.RS
Specify the GtkBuilder UI file.
.RE

.I --icon icon_file
.RS
Specify the icon file.
.RE

.SH FILES
.I ~/.meetings
.RS
\fIdiscuss\fR's list of meetings attended and transactions read.
.RE

.SH COPYRIGHT
Copyright 2013, Massachusetts Institute of Technology
.SH AUTHOR
Jonathan Reed, MIT IS&T

The original xdsc was written by Andy Oakland, MIT Project Athena
